version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka_network

  etl-service:
    build: ./etl-service
    depends_on:
      - kafka
    networks:
      - kafka_network

  data-generator:
    build: ./data-generator
    depends_on:
      - kafka
    networks:
      - kafka_network

  dashboard:
    build: ./dashboard
    ports:
      - "3001:3001"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
